### ISSUE TITLE
Create Sim Model Battery Values?

### ISSUE THREAD

**Issue by slowrunner** [iRobotEducation/create3_sim#117]
My non-Create robot worries a lot about his battery voltage and charging state both on and off his ancient iRobot dock.

The Create3 sim /battery_state topic is reporting 0v, 0 current, and 0 capacity.  
```
header:
  stamp:
    sec: 5
    nanosec: 514000000
  frame_id: base_link
voltage: 0.0
temperature: 0.0
current: 0.0
charge: 0.0
capacity: 0.0
design_capacity: 0.0
percentage: 1.0
power_supply_status: 0
power_supply_health: 0
power_supply_technology: 0
present: false
cell_voltage: []
cell_temperature: []
location: ''
serial_number: ''
---

```

Any chance the sim could start with a full battery and run it down at the Create3 moving load draw?

![Carl_Docked_Dec2020](https://user-images.githubusercontent.com/8950202/138981472-bc7642f8-10de-449d-a5a6-f8d8f90091ae.JPG)

Carl's life stats at the moment:
```
Total Life:  22154.2 hrs since Aug 22,2018
Life this year:  1570.2 hrs (BOY Aug 22)
Days Booted This Year:  4
Average Time Between Reboot:  392 hrs
Total Dockings:  2480
Dockings this year:  137
New Batteries At Cycle: 2160
Battery Set At Cycle:  320
Docking Failures this year:  3  or  2.1 % of Dockings
Safety Shutdowns this year:  1  or  .7 % of Dockings
Ave Cycle this year (w/o failures):  11.7 hours
Ave Cycle this year:  11.5 hours
Ave Playtime this year:  7.6
Ave of Last 10 Playtimes 7.5
Last Docking:  2021-10-26 14:34|[juicer.py.dock]---- Docking 2480 completed at 8.1 v after 7.4 h playtime
Last Recharge:  2021-10-26 18:35|[juicer.py.undock]---- Dismount 2480 at 10.9 v after 4.0 h recharge

```
