### ISSUE TITLE
Robot model flickers in rviz2

### ISSUE THREAD

**Issue by alsora** [iRobotEducation/create3_sim#73]
**Describe the bug**
Running the app in a ROS 2 Foxy docker container.
The robot model flickers a lot, it looks like there's a problem in the wheels TF publisher

**To Reproduce**
I'm using branch master
```
ros2 launch irobot_create_gazebo create3.launch.py
```

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/25433200/136392069-e4e254d9-950f-47dc-92a0-3b66b74391d2.mp4

**Comment by shuhaowu** [comment]
I think I also have problems with this bug. I noted that in the tf tree, the wheel frames are being broadcasted with a real timestamp while everything else is in sim time. Not sure if it is related or not, tho.

ros2 doctor doesn't show me anything either.

```
transforms:
- header:
    stamp:
      sec: 136
      nanosec: 321000000
    frame_id: odom
  child_frame_id: base_link
  transform:
    translation:
      x: 1.751332318387998
      y: -2.1631093830641075
      z: -0.0034154606198514154
    rotation:
      x: -0.00030014269185197413
      y: -0.0024524258137914663
      z: 0.14331001757702422
      w: -0.9896747619213424
---
transforms:
- header:
    stamp:
      sec: 1644555705
      nanosec: 258963110
    frame_id: wheel_drop_left
  child_frame_id: left_wheel
  transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: -0.0005212527839987735
      w: 0.9999998641477583

```
